# Generated by Django 6.0.5 on 2026-05-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0006_add_pass_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
