# Generated by Django 6.0.5 on 2026-05-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0009_add_message_media'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='like',
            new_name='dating_like_from_us_e7c489_idx',
            old_name='dating_like_from_to_idx',
        ),
        migrations.RenameIndex(
            model_name='like',
            new_name='dating_like_to_user_4449dc_idx',
            old_name='dating_like_to_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='like',
            new_name='dating_like_from_us_68b8a9_idx',
            old_name='dating_like_from_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='dating_matc_user1_i_4122c8_idx',
            old_name='dating_match_users_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='dating_matc_created_d1cc19_idx',
            old_name='dating_match_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='dating_mess_match_i_4d2ba9_idx',
            old_name='dating_msg_match_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='dating_mess_match_i_fb0ed1_idx',
            old_name='dating_msg_unread_idx',
        ),
        migrations.RenameIndex(
            model_name='pass',
            new_name='dating_pass_from_us_ebc91c_idx',
            old_name='dating_pass_from_to_idx',
        ),
        migrations.RenameIndex(
            model_name='pass',
            new_name='dating_pass_from_us_ff98b0_idx',
            old_name='dating_pass_from_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='dating_post_created_f51b8a_idx',
            old_name='dating_post_created_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='dating_post_user_id_b175fe_idx',
            old_name='dating_post_user_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='dating_user_hide_fr_361954_idx',
            old_name='dating_up_hide_ge_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='dating_user_updated_c19452_idx',
            old_name='dating_up_updated_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='campus',
            field=models.CharField(blank=True, help_text='University campus or location', max_length=150),
        ),
    ]
