# Generated by Django 6.0.5 on 2026-05-24 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0010_add_campus_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time the user was active', null=True),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-last_seen'], name='dating_user_last_se_199879_idx'),
        ),
    ]
